test s3 logger

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,18 +36,20 @@ jobs:
     - name: Check commit status
       id: commit-status
       run: |
-        # Check the status of the Git commit
-        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-        echo "Current status is: $CURRENT_STATUS"
-        while [ "${CURRENT_STATUS^^}" = "PENDING" ];
-          do sleep 10;
-          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-        done;
-        echo "Current status is: $CURRENT_STATUS"
-        if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
-          then echo "Commit status failed. Canceling execution";
-          exit 1;
-        fi
+        cd ./test/scripts
+        python ./s3_logger.py --sha ${{ github.sha }} --token ${{ secrets.GITHUB_TOKEN }}
+#        # Check the status of the Git commit
+#        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+#        echo "Current status is: $CURRENT_STATUS"
+#        while [ "${CURRENT_STATUS^^}" = "PENDING" ];
+#          do sleep 10;
+#          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+#        done;
+#        echo "Current status is: $CURRENT_STATUS"
+#        if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
+#          then echo "Commit status failed. Canceling execution";
+#          exit 1;
+#        fi
 
 #    - name: Install Blender test
 #      run: |
