on push

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,19 +36,39 @@ jobs:
       id: commit-status
       run: |
         cd ./test/scripts
-        python ./s3_logger.py --sha ${{ github.sha }} --token ${{ secrets.GITHUB_TOKEN }} --listen True
-#        # Check the status of the Git commit
-#        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-#        echo "Current status is: $CURRENT_STATUS"
-#        while [ "${CURRENT_STATUS^^}" = "PENDING" ];
-#          do sleep 10;
-#          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-#        done;
-#        echo "Current status is: $CURRENT_STATUS"
-#        if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
-#          then echo "Commit status failed. Canceling execution";
-#          exit 1;
-#        fi
+
+        # Check the status of the Git commit
+        CURRENT_STATUS=$(curl -sS --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+        echo "Current status is: $CURRENT_STATUS"
+        while [ "${CURRENT_STATUS^^}" = "PENDING" ];
+          do sleep 5;
+          python ./s3_logger.py --sha ${{ github.sha }} --listen True
+          output=$(python release_mail_generator.py v2.21)
+          output="${output//'%'/'%25'}"
+          output="${output//$'\n'/'%0A'}"
+          output="${output//$'\r'/'%0D'}"
+          echo $output
+
+          CURRENT_STATUS=$(curl -sS --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+        done;
+        echo "Current status is: $CURRENT_STATUS"
+        if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
+          python ./s3_logger.py --sha ${{ github.sha }} --listen True
+          output=$(python release_mail_generator.py v2.21)
+          output="${output//'%'/'%25'}"
+          output="${output//$'\n'/'%0A'}"
+          output="${output//$'\r'/'%0D'}"
+          echo $output
+          then echo "Commit status failed. Canceling execution";
+          exit 1;
+        fi
+
+        python ./s3_logger.py --sha ${{ github.sha }} --listen True
+        output=$(python release_mail_generator.py v2.21)
+        output="${output//'%'/'%25'}"
+        output="${output//$'\n'/'%0A'}"
+        output="${output//$'\r'/'%0D'}"
+        echo $output
 
 #    - name: Install Blender
 #      run: |
